name: Build and deploy Python project to Azure Function App - instana2bhom

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Top-level permissions enable OIDC tokens for all jobs.
permissions:
  id-token: write
  contents: read

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.12'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (optional) build / zip steps here if you want

      - name: Login to Azure (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6FA53E899C804754AF852297EBC1548F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_752857387786414399ECD99B46F4901D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_138C64700AF742FDB6F65073EE47ECD4 }}
          # no client-secret needed when using OIDC + id-token permission

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'instana2bhom'
          package: .
